# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1-main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window1(object):
    def setupUi(self, Window1):
        Window1.setObjectName("Window1")
        Window1.resize(805, 607)
        Window1.setMinimumSize(QtCore.QSize(805, 607))
        Window1.setMaximumSize(QtCore.QSize(805, 607))
        self.centralwidget = QtWidgets.QWidget(Window1)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 791, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(140, 90, 21, 491))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 801, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(270, 20, 241, 41))
        self.label.setLineWidth(5)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 90, 651, 491))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(140, 120, 321, 51))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 90, 151, 491))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_new = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_new.setGeometry(QtCore.QRect(30, 40, 91, 23))
        self.pushButton_new.setObjectName("pushButton_new")
        self.pushButton_all = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_all.setGeometry(QtCore.QRect(30, 70, 91, 23))
        self.pushButton_all.setObjectName("pushButton_all")
        self.pushButton_update = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_update.setGeometry(QtCore.QRect(30, 100, 91, 23))
        self.pushButton_update.setObjectName("pushButton_update")
        self.pushButton_del = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_del.setGeometry(QtCore.QRect(30, 160, 91, 23))
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_ierarx = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_ierarx.setGeometry(QtCore.QRect(30, 130, 91, 23))
        self.pushButton_ierarx.setObjectName("pushButton_ierarx")
        Window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        Window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window1)
        self.statusbar.setObjectName("statusbar")
        Window1.setStatusBar(self.statusbar)

        self.retranslateUi(Window1)
        QtCore.QMetaObject.connectSlotsByName(Window1)

    def retranslateUi(self, Window1):
        _translate = QtCore.QCoreApplication.translate
        Window1.setWindowTitle(_translate("Window1", "Основное окно"))
        self.label.setText(_translate("Window1", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Тестовое задание</span></p></body></html>"))
        self.label_2.setText(_translate("Window1", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Выберите операцию.</span></p></body></html>"))
        self.pushButton_new.setText(_translate("Window1", "Новая запись"))
        self.pushButton_all.setText(_translate("Window1", "Вывести всех"))
        self.pushButton_update.setText(_translate("Window1", "Редактировать"))
        self.pushButton_del.setText(_translate("Window1", "Удалить"))
        self.pushButton_ierarx.setText(_translate("Window1", "Иерархия"))
